DROP TABLE IF EXISTS User;


CREATE TABLE IF NOT EXISTS User (
  id          PRIMARY KEY       AUTO_INCREMENT,
  username    VARCHAR(255)      NOT NULL,
  password    VARCHAR(255)      NOT NULL,
  email       VARCHAR(255)      NOT NULL,
  createdAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  updatedAt   DATETIME DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  CONSTRAINT  UC_user UNIQUE (username, email)
);